// Base de capitais e cidades principais por UF para fallback offline imediato e seguro
export const CIDADES_FALLBACK_POR_UF: Record<string, string[]> = {
  AC: ['Rio Branco', 'Cruzeiro do Sul', 'Sena Madureira', 'Tarauacá', 'Feijó', 'Brasiléia'],
  AL: ['Maceió', 'Arapiraca', 'Rio Largo', 'Palmeira dos Índios', 'Penedo', 'União dos Palmares'],
  AP: ['Macapá', 'Santana', 'Laranjal do Jari', 'Oiapoque', 'Mazagão', 'Porto Grande'],
  AM: ['Manaus', 'Parintins', 'Itacoatiara', 'Manacapuru', 'Coari', 'Tefé'],
  BA: [
    'Salvador',
    'Feira de Santana',
    'Vitória da Conquista',
    'Camaçari',
    'Juazeiro',
    'Itabuna',
    'Lauro de Freitas',
    'Ilhéus',
    'Jequié',
    'Teixeira de Freitas',
    'Barreiras',
    'Porto Seguro',
  ],
  CE: [
    'Fortaleza',
    'Caucaia',
    'Juazeiro do Norte',
    'Maracanaú',
    'Sobral',
    'Crato',
    'Itapipoca',
    'Maranguape',
    'Iguatu',
  ],
  DF: [
    'Brasília',
    'Ceilândia',
    'Taguatinga',
    'Samambaia',
    'Plano Piloto',
    'Águas Claras',
    'Gama',
    'Guará',
    'Santa Maria',
  ],
  ES: [
    'Vitória',
    'Vila Velha',
    'Serra',
    'Cariacica',
    'Cachoeiro de Itapemirim',
    'Linhares',
    'Colatina',
    'Guarapari',
    'São Mateus',
  ],
  GO: [
    'Goiânia',
    'Aparecida de Goiânia',
    'Anápolis',
    'Rio Verde',
    'Luziânia',
    'Águas Lindas de Goiás',
    'Valparaíso de Goiás',
    'Trindade',
    'Formosa',
    'Itumbiara',
    'Senador Canedo',
    'Catalão',
  ],
  MA: [
    'São Luís',
    'Imperatriz',
    'São José de Ribamar',
    'Timon',
    'Caxias',
    'Codó',
    'Paço do Lumiar',
    'Açailândia',
    'Bacabal',
  ],
  MT: [
    'Cuiabá',
    'Várzea Grande',
    'Rondonópolis',
    'Sinop',
    'Tangará da Serra',
    'Sorriso',
    'Lucas do Rio Verde',
    'Primavera do Leste',
    'Barra do Garças',
  ],
  MS: [
    'Campo Grande',
    'Dourados',
    'Três Lagoas',
    'Corumbá',
    'Ponta Porã',
    'Naviraí',
    'Nova Andradina',
    'Sidrolândia',
  ],
  MG: [
    'Belo Horizonte',
    'Uberlândia',
    'Contagem',
    'Juiz de Fora',
    'Betim',
    'Montes Claros',
    'Ribeirão das Neves',
    'Uberaba',
    'Governador Valadares',
    'Ipatinga',
    'Sete Lagoas',
    'Divinópolis',
    'Santa Luzia',
    'Poços de Caldas',
  ],
  PA: [
    'Belém',
    'Ananindeua',
    'Santarém',
    'Marabá',
    'Parauapebas',
    'Castanhal',
    'Abaetetuba',
    'Cametá',
    'Marituba',
    'Bragança',
  ],
  PB: [
    'João Pessoa',
    'Campina Grande',
    'Santa Rita',
    'Patos',
    'Bayeux',
    'Sousa',
    'Cajazeiras',
    'Cabedelo',
    'Guarabira',
  ],
  PR: [
    'Curitiba',
    'Londrina',
    'Maringá',
    'Ponta Grossa',
    'Cascavel',
    'São José dos Pinhais',
    'Foz do Iguaçu',
    'Colombo',
    'Guarapuava',
    'Paranaguá',
    'Araucária',
    'Toledo',
    'Apucarana',
    'Pinhais',
    'Campo Largo',
  ],
  PE: [
    'Recife',
    'Jaboatão dos Guararapes',
    'Olinda',
    'Caruaru',
    'Petrolina',
    'Paulista',
    'Cabo de Santo Agostinho',
    'Camaragibe',
    'Garanhuns',
    'Vitória de Santo Antão',
  ],
  PI: ['Teresina', 'Parnaíba', 'Picos', 'Piripiri', 'Floriano', 'Barras', 'Campo Maior'],
  RJ: [
    'Rio de Janeiro',
    'São Gonçalo',
    'Duque de Caxias',
    'Nova Iguaçu',
    'Niterói',
    'Belford Roxo',
    'Campos dos Goytacazes',
    'São João de Meriti',
    'Petrópolis',
    'Volta Redonda',
    'Macaé',
    'Magé',
    'Itaboraí',
    'Cabo Frio',
    'Angra dos Reis',
    'Nova Friburgo',
    'Barra Mansa',
    'Teresópolis',
  ],
  RN: [
    'Natal',
    'Mossoró',
    'Parnamirim',
    'São Gonçalo do Amarante',
    'Ceará-Mirim',
    'Macaíba',
    'Caicó',
    'Açu',
  ],
  RS: [
    'Porto Alegre',
    'Caxias do Sul',
    'Canoas',
    'Pelotas',
    'Santa Maria',
    'Gravataí',
    'Viamão',
    'Novo Hamburgo',
    'São Leopoldo',
    'Rio Grande',
    'Alvorada',
    'Passo Fundo',
    'Sapucaia do Sul',
    'Uruguaiana',
    'Santa Cruz do Sul',
  ],
  RO: [
    'Porto Velho',
    'Ji-Paraná',
    'Ariquemes',
    'Vilhena',
    'Cacoal',
    'Rolim de Moura',
    'Jaru',
    'Guajará-Mirim',
  ],
  RR: ['Boa Vista', 'Rorainópolis', 'Caracaraí', 'Cantá', 'Mucajaí'],
  SC: [
    'Florianópolis',
    'Joinville',
    'Blumenau',
    'São José',
    'Chapecó',
    'Itajaí',
    'Criciúma',
    'Jaraguá do Sul',
    'Palhoça',
    'Lages',
    'Balneário Camboriú',
    'Brusque',
    'Tubarão',
    'São Bento do Sul',
  ],
  SP: [
    'São Paulo',
    'Guarulhos',
    'Campinas',
    'São Bernardo do Campo',
    'São José dos Campos',
    'Santo André',
    'Ribeirão Preto',
    'Osasco',
    'Sorocaba',
    'Mauá',
    'São José do Rio Preto',
    'Mogi das Cruzes',
    'Santos',
    'Diadema',
    'Jundiaí',
    'Piracicaba',
    'Carapicuíba',
    'Bauru',
    'Itaquaquecetuba',
    'São Vicente',
    'Franca',
    'Praia Grande',
    'Guarujá',
    'Taubaté',
    'Limeira',
    'Suzano',
    'Taboão da Serra',
    'Sumaré',
    'Barueri',
    'Embu das Artes',
    'Cotia',
    'Americana',
    'Marília',
    'Araraquara',
    'Jacareí',
    'Presidente Prudente',
  ],
  SE: ['Aracaju', 'Nossa Senhora do Socorro', 'Lagarto', 'Itabaiana', 'São Cristóvão', 'Estância'],
  TO: [
    'Palmas',
    'Araguaína',
    'Gurupi',
    'Porto Nacional',
    'Paraíso do Tocantins',
    'Colinas do Tocantins',
  ],
}

// Cache local em memória para evitar requisições repetidas ao IBGE
const ibgeCache = new Map<string, string[]>()

/**
 * Busca cidades brasileiras por UF na API oficial do IBGE com fallback e ordenação alfabética
 */
export async function getCidadesPorUf(uf: string): Promise<string[]> {
  const ufUpper = (uf || '').trim().toUpperCase()
  if (!ufUpper) return []

  if (ibgeCache.has(ufUpper)) {
    return ibgeCache.get(ufUpper)!
  }

  try {
    const controller = new AbortController()
    const timeout = setTimeout(() => controller.abort(), 4000)

    const response = await fetch(
      `https://servicodados.ibge.gov.br/api/v1/localidades/estados/${ufUpper}/municipios?orderBy=nome`,
      { signal: controller.signal },
    )
    clearTimeout(timeout)

    if (response.ok) {
      const data = await response.json()
      if (Array.isArray(data) && data.length > 0) {
        const nomes: string[] = data.map((m: any) => m.nome).filter(Boolean)
        ibgeCache.set(ufUpper, nomes)
        return nomes
      }
    }
  } catch (err) {
    console.warn(
      `[IBGE] Falha ao carregar municípios de ${ufUpper}, utilizando fallback offline:`,
      err,
    )
  }

  // Fallback offline caso API esteja indisponível ou lenta
  const fallback = CIDADES_FALLBACK_POR_UF[ufUpper] || []
  return fallback
}
